name: flutter_upload_file_new
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # navigation
  go_router: ^9.0.0
  # dependency injection
  get_it: ^7.6.4
  # netwok
  dio: ^5.3.3
  # state management
  flutter_bloc: ^8.1.3
  # widget library
  dotted_border: ^2.1.0
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  video_player: ^2.7.2
  # utils
  uuid: ^4.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  # utils
  build_runner: ^2.3.0
  freezed: ^2.4.3
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
